---
title: "Example 2"
output: rmarkdown::html_vignette
css: css/pmxpartab_defaults.css
vignette: >
  %\VignetteIndexEntry{Example 2}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

Example with all information in the yaml file (except from parameter name). No bootstrap information available (ie, CI calculated with normal distribution assumptions).
  
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

# Setup environment
```{r envir, message = FALSE, warning = FALSE}

# ----- Load package -----
library(pmxpartabc)

# ----- Define directory and file names -----
run_dir    <- file.path(system.file(package = "pmxpartabc"), "examples")
run_prefix <- "run"
runno     <-  "6"
yaml.file.name <- file.path(system.file(package = "pmxpartabc"), "meta.yaml")
```

# Parameter table 1 - using yaml file
```{r all-runs-1, results='asis', warning = FALSE}

output <- parframe2setup(run_dir, 
                      run_prefix, 
                      runno, 
                      conf.level = 0.95, 
                      min_suc = TRUE, 
                      yaml.file = TRUE, 
                      yaml.file.name = yaml.file.name)

tab=parframe(out=output[[1]], meta=output[[2]])  

tab1=pmxpartab(tab, output[[2]], columns=c(value="Estimate", rse="RSE%", ci95="95%CI", shrinkage="Shrinkage"))

print(tab1)

```

# Session information
```{r session-info}

sessionInfo()

```

