---
title: "Working examples of parameter tables"
subtitle: "Parameter table for final model"

output:
  html_document:
  toc : yes
toc_float: yes
df_print: paged
theme: lumen
number_sections: yes
css: pmxpartab_defaults.css

knitr: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
                    output_format = "html_document") })
---

Example with all information in the yaml file (except from parameter name). No bootstrap information available (ie, CI calculated with normal distribution assumptions).
  
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

# Setup environment
```{r envir, message = FALSE, warning = FALSE}

# ----- Load libraries -----
library(tidyverse)
library(knitr)
library(xpose)
library(yaml)
library(htmltools)

# ----- Load functions  -----
source("functions.r")

# ----- Define directory and file names -----
run_dir    <- '../examples/'
run_prefix <- "run"
runno     <-  "6"

```

# Parameter table 1 - using yaml file
```{r all-runs-1, results='asis', warning = FALSE}

output=parframe2setup(run_dir, run_prefix, runno, conf.level = 0.95, min_suc = TRUE, yaml.file = TRUE, yaml.file.name = 'meta.yaml')

tab=parframe(out=output[[1]], meta=output[[2]])  

tab1=pmxpartab(tab, output[[2]], columns=c(value="Estimate", rse="RSE%", ci95="95%CI", shrinkage="Shrinkage"))

print(tab1)

```

# Session information
```{r session-info}

sessionInfo()

```

