---
namemap: 
  theta:
    - V2  
    - CL
    - V3
    - Q
    - KA
    - ERRPROP
  omega:
    - nV2
    - nCL    
    - nV3
    - nQ
    - nKA

parameters:
  - name: V2
    label: Central volume
    units: L
    trans: 
    type: Structural

  - name: CL
    label: Clearance
    units: L/h
    trans: 
    type: Structural
    
  - name: V3
    label: Peripheral volume
    units: L
    trans: 
    type: Structural    
  
  - name: Q
    label: Peripheral clearance
    units: L/h
    trans: 
    type: Structural

  - name: KA
    label: Absorption rate constant
    units: "h<sup>-1</sup>"
    trans: 
    type: Structural
    
  - name: nV2
    label: On Central volume
    type: IIV     
       
  - name: nCL,nV2
    label: Correlation on Clearance, on Central Volume
    type: IIV   
    
  - name: nCL
    label: On Clearance
    type: IIV
        
  - name: nV3
    label: On V3
    type: IIV

  - name: nQ
    label: On Q
    type: IIV

  - name: nKA
    label: On Ka
    type: IIV

  - name: ERRPROP
    label: Proportional Error
    units: '-'
    trans: 
    type: RUV

